job_parsing_task:
  description: >
    Analyze the provided job description and create a detailed report with the following sections:

    {job_description}

    Format the output as a structured markdown document with clear sections and bullet points.
    Also include a summary section at the top with the key variables that will be used for interpolation.
  expected_output: >
    A detailed markdown document analyzing all aspects of the job posting,
    with a special focus on extracting structured information that can be
    used by other agents. Include both the raw extracted data and your analysis
    of implicit requirements and context.
  agent: job_parser
  output_file: output/00_job_parsing.md

company_research_task:
  description: >
    Using the parsed information from the previous task, conduct research about the company:
    - Industry sector
    - Company type
    - Key technologies
    - Main challenges in the sector
  expected_output: >
    A concise industry context report that helps understand the technical
    requirements and business domain for the role.
  agent: company_researcher
  depends_on: ["job_parsing_task"]
  output_file: output/01_company_analysis.md

job_analysis_task:
  description: >
    Based on the industry context from the previous tasks:
    - Focus on the required skills needed in the industry
    - Identify which techniques are most relevant for the role
    - Map how technology can solve industry-specific challenges
    - Note any regulations and compliance requirements
  expected_output: >
    Analysis of how the required skills specifically apply to this industry context.
  agent: job_analyzer
  depends_on: ["company_research_task"]
  output_file: output/02_job_analysis.md

question_generation_task:
  description: >
    Using the job analysis context from previous tasks:
    - Questions about handling industry-specific data
    - Technical scenarios for the role
    - Questions about core skills
    - Industry-specific challenges
  expected_output: >
    Technical questions that combine required expertise with industry domain knowledge.
  agent: interview_question_generator
  depends_on: ["job_analysis_task"]
  output_file: output/03_interview_questions.md

answer_generation_task:
  description: >
    Create example answers based on all previous analysis:
    - Code examples using industry scenarios
    - Technical solutions for industry challenges
    - Best practices for core skills
    - Industry-specific implementation approaches
  expected_output: >
    Sample answers that demonstrate both technical skills and industry domain knowledge.
  agent: answer_generator
  depends_on: ["question_generation_task"]
  output_file: output/04_interview_answers.md
