extract_task:
  description: >
    Analiza la siguiente descripción de trabajo:
    {job_description}
    
    Extrae y estructura la siguiente información:
    1. Título del puesto
    2. Empresa
    3. Requisitos técnicos
    4. Responsabilidades
    5. Beneficios
  expected_output: >
    # Análisis del Puesto

    ## Información General
    - Puesto: [título]
    - Empresa: [nombre]
    - Ubicación: [ubicación]

    ## Requisitos Técnicos
    - [lista de habilidades y tecnologías]

    ## Responsabilidades
    - [lista de responsabilidades]

    ## Beneficios
    - [lista de beneficios]

research_task:
  description: >
    Basado en el análisis anterior, genera preguntas técnicas específicas 
    que evalúen las habilidades requeridas para el puesto.
    Enfócate en los requisitos técnicos y responsabilidades identificadas.
  expected_output: >
    # Preguntas para la Entrevista

    ## Preguntas Técnicas
    1. [pregunta sobre habilidad específica]
    2. [pregunta sobre tecnología requerida]
    3. [pregunta sobre experiencia relevante]

    ## Preguntas sobre Proyectos
    1. [pregunta sobre implementación]
    2. [pregunta sobre resolución de problemas]
    3. [pregunta sobre metodología]

hr_task:
  description: >
    Basado en el análisis del puesto y la cultura de la empresa,
    genera preguntas de comportamiento y ajuste cultural que evalúen
    las habilidades blandas y el potencial del candidato.
  expected_output: >
    # Preguntas de RRHH

    ## Preguntas de Comportamiento
    1. [pregunta sobre trabajo en equipo]
    2. [pregunta sobre manejo de conflictos]
    3. [pregunta sobre liderazgo]

    ## Preguntas de Ajuste Cultural
    1. [pregunta sobre valores]
    2. [pregunta sobre motivación]
    3. [pregunta sobre desarrollo profesional]

interview_task:
  description: >
    Basado en las preguntas técnicas y de RRHH generadas anteriormente,
    proporciona respuestas modelo detalladas que demuestren experiencia y competencia.
    Las respuestas deben incluir ejemplos concretos y seguir las mejores prácticas del sector.
    
    Asegúrate de cubrir tanto las preguntas técnicas como las de comportamiento,
    y proporciona consejos específicos para cada tipo de pregunta.
  expected_output: >
    # Guía de Respuestas

    ## Respuestas Técnicas
    1. [respuesta detallada con ejemplo técnico]
    2. [respuesta detallada con ejemplo técnico]
    3. [respuesta detallada con ejemplo técnico]

    ## Respuestas de Comportamiento
    1. [respuesta detallada con ejemplo de situación]
    2. [respuesta detallada con ejemplo de situación]
    3. [respuesta detallada con ejemplo de situación]

    ## Consejos para la Entrevista
    - [consejos para respuestas técnicas]
    - [consejos para respuestas de comportamiento]
    - [consejos generales]
