company_research_task:
  description: >
    Provide essential context about {company_name}:
    - Industry sector and main business focus
    - Type of organization (hospital, insurance, tech company, etc.)
    - Key technologies or systems commonly used in this sector
    - Main challenges and trends in the industry
  expected_output: >
    A concise industry context report that helps understand the technical
    requirements and business domain for the role.
  agent: company_researcher
  output_file: output/01_company_analysis.md

job_analysis_task:
  description: >
    Based on the industry context for {job_title} at {company_name}:
    - Focus on data science skills needed in healthcare/insurance
    - Identify which data science techniques are most relevant
    - Map how ML/AI can solve industry-specific challenges
    - Note data privacy and healthcare regulations that affect DS work
  expected_output: >
    Analysis of how data science specifically applies to this healthcare context.
  agent: job_analyzer
  depends_on: ["company_research_task"]
  output_file: output/02_job_analysis.md

question_generation_task:
  description: >
    Using the job analysis context, generate data science questions specific to healthcare:
    - Questions about handling medical claims data
    - ML scenarios for health risk prediction
    - Data privacy and compliance questions
    - Healthcare-specific data analysis challenges
  expected_output: >
    Technical questions that combine data science expertise with healthcare domain knowledge.
  agent: interview_question_generator
  depends_on: ["job_analysis_task"]
  output_file: output/03_interview_questions.md

answer_generation_task:
  description: >
    Create example answers showing healthcare data science expertise:
    - Code examples using medical data scenarios
    - ML solutions for healthcare challenges
    - Data privacy compliance approaches
    - Healthcare analytics best practices
  expected_output: >
    Sample answers that demonstrate both data science skills and healthcare domain knowledge.
  agent: answer_generator
  depends_on: ["question_generation_task"]
  output_file: output/04_interview_answers.md
