company_research_task:
  description: >
    Research and analyze {company_name} to understand:
    - Company background and history
    - Main products/services
    - Company culture and values
    - Recent news and developments
    - Market position and competitors
  expected_output: >
    A detailed markdown report containing company insights that will be valuable
    for interview preparation and contextualizing questions.
  agent: company_researcher
  output_file: interview_prep.md

job_analysis_task:
  description: >
    Analyze the provided job description for {job_title} at {company_name}:
    - Extract technical requirements and skills
    - Identify soft skills and cultural requirements
    - List main responsibilities
    - Note any specific industry knowledge required
    Use the company research context to enhance the analysis.
  expected_output: >
    A structured markdown document containing categorized job requirements,
    skills, and responsibilities.
  agent: job_analyzer
  append_to_file: interview_prep.md

question_generation_task:
  description: >
    Using the job analysis and company research, generate:
    - Technical questions based on required skills and technologies
    - Behavioral questions focused on responsibilities and company culture
    - Questions about the company that show research and interest
    Make questions specific to {job_title} role at {company_name}.
  expected_output: >
    A comprehensive list of interview questions categorized by type
    (technical, behavioral, company-specific) in markdown format.
  agent: interview_question_generator
  append_to_file: interview_prep.md

answer_generation_task:
  description: >
    Create example answers for the generated questions:
    - Technical answers with code examples where appropriate
    - STAR-formatted answers for behavioral questions
    - Strategic answers about company knowledge
    Ensure answers align with {company_name}'s culture and {job_title} requirements.
  expected_output: >
    A detailed markdown document with example answers for each question,
    including code snippets and STAR-formatted responses.
  agent: answer_generator
  append_to_file: interview_prep.md
