extract_task:
  description: >
    Analiza la siguiente descripción de trabajo:
    {job_description}
    
    Extrae y estructura la siguiente información:
    1. Título del puesto
    2. Empresa
    3. Requisitos técnicos
    4. Responsabilidades
    5. Beneficios
  expected_output: >
    # Análisis del Puesto

    ## Información General
    - Puesto: [título]
    - Empresa: [nombre]
    - Ubicación: [ubicación]

    ## Requisitos Técnicos
    - [lista de habilidades y tecnologías]

    ## Responsabilidades
    - [lista de responsabilidades]

    ## Beneficios
    - [lista de beneficios]

research_task:
  description: >
    Basado en el análisis anterior, genera preguntas técnicas específicas 
    que evalúen las habilidades requeridas para el puesto.
    Enfócate en los requisitos técnicos y responsabilidades identificadas.
  expected_output: >
    # Preguntas para la Entrevista

    ## Preguntas Técnicas
    1. [pregunta sobre habilidad específica]
    2. [pregunta sobre tecnología requerida]
    3. [pregunta sobre experiencia relevante]

    ## Preguntas sobre Proyectos
    1. [pregunta sobre implementación]
    2. [pregunta sobre resolución de problemas]
    3. [pregunta sobre metodología]

interview_task:
  description: >
    Proporciona respuestas modelo para las preguntas técnicas generadas.
    Incluye ejemplos prácticos y mejores prácticas del sector.
  expected_output: >
    # Guía de Respuestas

    ## Respuestas Técnicas
    1. [respuesta detallada con ejemplo]
    2. [respuesta detallada con ejemplo]
    3. [respuesta detallada con ejemplo]

    ## Consejos para la Entrevista
    - [consejo sobre cómo estructurar respuestas]
    - [consejo sobre puntos clave]
    - [consejo sobre ejemplos a mencionar]
