job_parsing_task:
  description: >
    Analyze the provided job description and create a detailed report with the following sections:

    1. COMPANY INFORMATION
    - Company Name: {Extraído}
    - Industry Sector: {Extraído}
    - Company Type: {Extraído}
    - Company Culture: {Análisis de valores y cultura}
    
    2. POSITION DETAILS
    - Job Title: {Extraído}
    - Seniority Level: {Análisis basado en requisitos}
    - Work Mode: {Remote/Hybrid/Office}
    - Location: {Extraído}
    
    3. TECHNICAL REQUIREMENTS
    - Core Skills: {Lista de skills principales}
    - Technical Stack: {Tecnologías mencionadas}
    - Experience Level: {Años y tipo de experiencia}
    
    4. ADDITIONAL CONTEXT
    - Team Structure: {Análisis del contexto de equipo}
    - Project Focus: {Áreas de trabajo principales}
    - Industry-Specific Requirements: {Requisitos específicos del sector}

    Format the output as a structured markdown document with clear sections and bullet points.
    Also include a summary section at the top with the key variables that will be used for interpolation.
  expected_output: >
    A detailed markdown document analyzing all aspects of the job posting,
    with a special focus on extracting structured information that can be
    used by other agents. Include both the raw extracted data and your analysis
    of implicit requirements and context.
  agent: job_parser
  output_file: output/00_job_parsing.md

company_research_task:
  description: >
    Using the parsed information, provide essential context about the company:
    - Industry sector: {industry_sector}
    - Company type: {company_type}
    - Key technologies: {tech_stack}
    - Main challenges in this sector
  expected_output: >
    A concise industry context report that helps understand the technical
    requirements and business domain for the role.
  agent: company_researcher
  depends_on: ["job_parsing_task"]
  output_file: output/01_company_analysis.md

job_analysis_task:
  description: >
    Based on the industry context for {job_title} at {company_name}:
    - Focus on data science skills needed in healthcare/insurance
    - Identify which data science techniques are most relevant
    - Map how ML/AI can solve industry-specific challenges
    - Note data privacy and healthcare regulations that affect DS work
  expected_output: >
    Analysis of how data science specifically applies to this healthcare context.
  agent: job_analyzer
  depends_on: ["company_research_task"]
  output_file: output/02_job_analysis.md

question_generation_task:
  description: >
    Using the job analysis context, generate data science questions specific to healthcare:
    - Questions about handling medical claims data
    - ML scenarios for health risk prediction
    - Data privacy and compliance questions
    - Healthcare-specific data analysis challenges
  expected_output: >
    Technical questions that combine data science expertise with healthcare domain knowledge.
  agent: interview_question_generator
  depends_on: ["job_analysis_task"]
  output_file: output/03_interview_questions.md

answer_generation_task:
  description: >
    Create example answers showing healthcare data science expertise:
    - Code examples using medical data scenarios
    - ML solutions for healthcare challenges
    - Data privacy compliance approaches
    - Healthcare analytics best practices
  expected_output: >
    Sample answers that demonstrate both data science skills and healthcare domain knowledge.
  agent: answer_generator
  depends_on: ["question_generation_task"]
  output_file: output/04_interview_answers.md
